// Generated by gencpp from file dg_msgs/BollardOperationGoal.msg
// DO NOT EDIT!


#ifndef DG_MSGS_MESSAGE_BOLLARDOPERATIONGOAL_H
#define DG_MSGS_MESSAGE_BOLLARDOPERATIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dg_msgs
{
template <class ContainerAllocator>
struct BollardOperationGoal_
{
  typedef BollardOperationGoal_<ContainerAllocator> Type;

  BollardOperationGoal_()
    : bollard_index(0)
    , target_height(0.0)  {
    }
  BollardOperationGoal_(const ContainerAllocator& _alloc)
    : bollard_index(0)
    , target_height(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _bollard_index_type;
  _bollard_index_type bollard_index;

   typedef float _target_height_type;
  _target_height_type target_height;





  typedef boost::shared_ptr< ::dg_msgs::BollardOperationGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dg_msgs::BollardOperationGoal_<ContainerAllocator> const> ConstPtr;

}; // struct BollardOperationGoal_

typedef ::dg_msgs::BollardOperationGoal_<std::allocator<void> > BollardOperationGoal;

typedef boost::shared_ptr< ::dg_msgs::BollardOperationGoal > BollardOperationGoalPtr;
typedef boost::shared_ptr< ::dg_msgs::BollardOperationGoal const> BollardOperationGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dg_msgs::BollardOperationGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dg_msgs::BollardOperationGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dg_msgs::BollardOperationGoal_<ContainerAllocator1> & lhs, const ::dg_msgs::BollardOperationGoal_<ContainerAllocator2> & rhs)
{
  return lhs.bollard_index == rhs.bollard_index &&
    lhs.target_height == rhs.target_height;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dg_msgs::BollardOperationGoal_<ContainerAllocator1> & lhs, const ::dg_msgs::BollardOperationGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dg_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::dg_msgs::BollardOperationGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dg_msgs::BollardOperationGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dg_msgs::BollardOperationGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dg_msgs::BollardOperationGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dg_msgs::BollardOperationGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dg_msgs::BollardOperationGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dg_msgs::BollardOperationGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "62a5e93afe45cf5dbd5ae2139afb485b";
  }

  static const char* value(const ::dg_msgs::BollardOperationGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x62a5e93afe45cf5dULL;
  static const uint64_t static_value2 = 0xbd5ae2139afb485bULL;
};

template<class ContainerAllocator>
struct DataType< ::dg_msgs::BollardOperationGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dg_msgs/BollardOperationGoal";
  }

  static const char* value(const ::dg_msgs::BollardOperationGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dg_msgs::BollardOperationGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# 升降柱动作action服务\n"
"int32 bollard_index                         # 升降柱序号\n"
"float32 target_height                       # 目标高度\n"
;
  }

  static const char* value(const ::dg_msgs::BollardOperationGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dg_msgs::BollardOperationGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bollard_index);
      stream.next(m.target_height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BollardOperationGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dg_msgs::BollardOperationGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dg_msgs::BollardOperationGoal_<ContainerAllocator>& v)
  {
    s << indent << "bollard_index: ";
    Printer<int32_t>::stream(s, indent + "  ", v.bollard_index);
    s << indent << "target_height: ";
    Printer<float>::stream(s, indent + "  ", v.target_height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DG_MSGS_MESSAGE_BOLLARDOPERATIONGOAL_H
