// Generated by gencpp from file dg_msgs/BollardPauseRecvTerm.msg
// DO NOT EDIT!


#ifndef DG_MSGS_MESSAGE_BOLLARDPAUSERECVTERM_H
#define DG_MSGS_MESSAGE_BOLLARDPAUSERECVTERM_H

#include <ros/service_traits.h>


#include <dg_msgs/BollardPauseRecvTermRequest.h>
#include <dg_msgs/BollardPauseRecvTermResponse.h>


namespace dg_msgs
{

struct BollardPauseRecvTerm
{

typedef BollardPauseRecvTermRequest Request;
typedef BollardPauseRecvTermResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BollardPauseRecvTerm
} // namespace dg_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dg_msgs::BollardPauseRecvTerm > {
  static const char* value()
  {
    return "79a8946e4b3e453cc2c4ad94be08ff4e";
  }

  static const char* value(const ::dg_msgs::BollardPauseRecvTerm&) { return value(); }
};

template<>
struct DataType< ::dg_msgs::BollardPauseRecvTerm > {
  static const char* value()
  {
    return "dg_msgs/BollardPauseRecvTerm";
  }

  static const char* value(const ::dg_msgs::BollardPauseRecvTerm&) { return value(); }
};


// service_traits::MD5Sum< ::dg_msgs::BollardPauseRecvTermRequest> should match
// service_traits::MD5Sum< ::dg_msgs::BollardPauseRecvTerm >
template<>
struct MD5Sum< ::dg_msgs::BollardPauseRecvTermRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dg_msgs::BollardPauseRecvTerm >::value();
  }
  static const char* value(const ::dg_msgs::BollardPauseRecvTermRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dg_msgs::BollardPauseRecvTermRequest> should match
// service_traits::DataType< ::dg_msgs::BollardPauseRecvTerm >
template<>
struct DataType< ::dg_msgs::BollardPauseRecvTermRequest>
{
  static const char* value()
  {
    return DataType< ::dg_msgs::BollardPauseRecvTerm >::value();
  }
  static const char* value(const ::dg_msgs::BollardPauseRecvTermRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dg_msgs::BollardPauseRecvTermResponse> should match
// service_traits::MD5Sum< ::dg_msgs::BollardPauseRecvTerm >
template<>
struct MD5Sum< ::dg_msgs::BollardPauseRecvTermResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dg_msgs::BollardPauseRecvTerm >::value();
  }
  static const char* value(const ::dg_msgs::BollardPauseRecvTermResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dg_msgs::BollardPauseRecvTermResponse> should match
// service_traits::DataType< ::dg_msgs::BollardPauseRecvTerm >
template<>
struct DataType< ::dg_msgs::BollardPauseRecvTermResponse>
{
  static const char* value()
  {
    return DataType< ::dg_msgs::BollardPauseRecvTerm >::value();
  }
  static const char* value(const ::dg_msgs::BollardPauseRecvTermResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DG_MSGS_MESSAGE_BOLLARDPAUSERECVTERM_H
