// Generated by gencpp from file dg_msgs/CameraTargetOrderResponse.msg
// DO NOT EDIT!


#ifndef DG_MSGS_MESSAGE_CAMERATARGETORDERRESPONSE_H
#define DG_MSGS_MESSAGE_CAMERATARGETORDERRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float64MultiArray.h>

namespace dg_msgs
{
template <class ContainerAllocator>
struct CameraTargetOrderResponse_
{
  typedef CameraTargetOrderResponse_<ContainerAllocator> Type;

  CameraTargetOrderResponse_()
    : order_index()
    , multi_joint_data()  {
    }
  CameraTargetOrderResponse_(const ContainerAllocator& _alloc)
    : order_index(_alloc)
    , multi_joint_data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _order_index_type;
  _order_index_type order_index;

   typedef std::vector< ::std_msgs::Float64MultiArray_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::std_msgs::Float64MultiArray_<ContainerAllocator> >> _multi_joint_data_type;
  _multi_joint_data_type multi_joint_data;





  typedef boost::shared_ptr< ::dg_msgs::CameraTargetOrderResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dg_msgs::CameraTargetOrderResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CameraTargetOrderResponse_

typedef ::dg_msgs::CameraTargetOrderResponse_<std::allocator<void> > CameraTargetOrderResponse;

typedef boost::shared_ptr< ::dg_msgs::CameraTargetOrderResponse > CameraTargetOrderResponsePtr;
typedef boost::shared_ptr< ::dg_msgs::CameraTargetOrderResponse const> CameraTargetOrderResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dg_msgs::CameraTargetOrderResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dg_msgs::CameraTargetOrderResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dg_msgs::CameraTargetOrderResponse_<ContainerAllocator1> & lhs, const ::dg_msgs::CameraTargetOrderResponse_<ContainerAllocator2> & rhs)
{
  return lhs.order_index == rhs.order_index &&
    lhs.multi_joint_data == rhs.multi_joint_data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dg_msgs::CameraTargetOrderResponse_<ContainerAllocator1> & lhs, const ::dg_msgs::CameraTargetOrderResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dg_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::dg_msgs::CameraTargetOrderResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dg_msgs::CameraTargetOrderResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dg_msgs::CameraTargetOrderResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dg_msgs::CameraTargetOrderResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dg_msgs::CameraTargetOrderResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dg_msgs::CameraTargetOrderResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dg_msgs::CameraTargetOrderResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "39b33a8637c95e13516daeef4683dc68";
  }

  static const char* value(const ::dg_msgs::CameraTargetOrderResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x39b33a8637c95e13ULL;
  static const uint64_t static_value2 = 0x516daeef4683dc68ULL;
};

template<class ContainerAllocator>
struct DataType< ::dg_msgs::CameraTargetOrderResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dg_msgs/CameraTargetOrderResponse";
  }

  static const char* value(const ::dg_msgs::CameraTargetOrderResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dg_msgs::CameraTargetOrderResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[]                      order_index\n"
"std_msgs/Float64MultiArray[] multi_joint_data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float64MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"float64[]         data          # array of data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayLayout\n"
"# The multiarray declares a generic multi-dimensional array of a\n"
"# particular data type.  Dimensions are ordered from outer most\n"
"# to inner most.\n"
"\n"
"MultiArrayDimension[] dim # Array of dimension properties\n"
"uint32 data_offset        # padding elements at front of data\n"
"\n"
"# Accessors should ALWAYS be written in terms of dimension stride\n"
"# and specified outer-most dimension first.\n"
"# \n"
"# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n"
"#\n"
"# A standard, 3-channel 640x480 image with interleaved color channels\n"
"# would be specified as:\n"
"#\n"
"# dim[0].label  = \"height\"\n"
"# dim[0].size   = 480\n"
"# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n"
"# dim[1].label  = \"width\"\n"
"# dim[1].size   = 640\n"
"# dim[1].stride = 3*640 = 1920\n"
"# dim[2].label  = \"channel\"\n"
"# dim[2].size   = 3\n"
"# dim[2].stride = 3\n"
"#\n"
"# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayDimension\n"
"string label   # label of given dimension\n"
"uint32 size    # size of given dimension (in type units)\n"
"uint32 stride  # stride of given dimension\n"
;
  }

  static const char* value(const ::dg_msgs::CameraTargetOrderResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dg_msgs::CameraTargetOrderResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.order_index);
      stream.next(m.multi_joint_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CameraTargetOrderResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dg_msgs::CameraTargetOrderResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dg_msgs::CameraTargetOrderResponse_<ContainerAllocator>& v)
  {
    s << indent << "order_index[]" << std::endl;
    for (size_t i = 0; i < v.order_index.size(); ++i)
    {
      s << indent << "  order_index[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.order_index[i]);
    }
    s << indent << "multi_joint_data[]" << std::endl;
    for (size_t i = 0; i < v.multi_joint_data.size(); ++i)
    {
      s << indent << "  multi_joint_data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::std_msgs::Float64MultiArray_<ContainerAllocator> >::stream(s, indent + "    ", v.multi_joint_data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DG_MSGS_MESSAGE_CAMERATARGETORDERRESPONSE_H
