// Generated by gencpp from file dg_msgs/CameraDataCollect.msg
// DO NOT EDIT!


#ifndef DG_MSGS_MESSAGE_CAMERADATACOLLECT_H
#define DG_MSGS_MESSAGE_CAMERADATACOLLECT_H

#include <ros/service_traits.h>


#include <dg_msgs/CameraDataCollectRequest.h>
#include <dg_msgs/CameraDataCollectResponse.h>


namespace dg_msgs
{

struct CameraDataCollect
{

typedef CameraDataCollectRequest Request;
typedef CameraDataCollectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CameraDataCollect
} // namespace dg_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dg_msgs::CameraDataCollect > {
  static const char* value()
  {
    return "c67c27276579d6590e6569ff105e6071";
  }

  static const char* value(const ::dg_msgs::CameraDataCollect&) { return value(); }
};

template<>
struct DataType< ::dg_msgs::CameraDataCollect > {
  static const char* value()
  {
    return "dg_msgs/CameraDataCollect";
  }

  static const char* value(const ::dg_msgs::CameraDataCollect&) { return value(); }
};


// service_traits::MD5Sum< ::dg_msgs::CameraDataCollectRequest> should match
// service_traits::MD5Sum< ::dg_msgs::CameraDataCollect >
template<>
struct MD5Sum< ::dg_msgs::CameraDataCollectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dg_msgs::CameraDataCollect >::value();
  }
  static const char* value(const ::dg_msgs::CameraDataCollectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dg_msgs::CameraDataCollectRequest> should match
// service_traits::DataType< ::dg_msgs::CameraDataCollect >
template<>
struct DataType< ::dg_msgs::CameraDataCollectRequest>
{
  static const char* value()
  {
    return DataType< ::dg_msgs::CameraDataCollect >::value();
  }
  static const char* value(const ::dg_msgs::CameraDataCollectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dg_msgs::CameraDataCollectResponse> should match
// service_traits::MD5Sum< ::dg_msgs::CameraDataCollect >
template<>
struct MD5Sum< ::dg_msgs::CameraDataCollectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dg_msgs::CameraDataCollect >::value();
  }
  static const char* value(const ::dg_msgs::CameraDataCollectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dg_msgs::CameraDataCollectResponse> should match
// service_traits::DataType< ::dg_msgs::CameraDataCollect >
template<>
struct DataType< ::dg_msgs::CameraDataCollectResponse>
{
  static const char* value()
  {
    return DataType< ::dg_msgs::CameraDataCollect >::value();
  }
  static const char* value(const ::dg_msgs::CameraDataCollectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DG_MSGS_MESSAGE_CAMERADATACOLLECT_H
