// Generated by gencpp from file dg_msgs/ChannelAligning.msg
// DO NOT EDIT!


#ifndef DG_MSGS_MESSAGE_CHANNELALIGNING_H
#define DG_MSGS_MESSAGE_CHANNELALIGNING_H

#include <ros/service_traits.h>


#include <dg_msgs/ChannelAligningRequest.h>
#include <dg_msgs/ChannelAligningResponse.h>


namespace dg_msgs
{

struct ChannelAligning
{

typedef ChannelAligningRequest Request;
typedef ChannelAligningResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ChannelAligning
} // namespace dg_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dg_msgs::ChannelAligning > {
  static const char* value()
  {
    return "7a688dfc87e588c1b04a6359014918f4";
  }

  static const char* value(const ::dg_msgs::ChannelAligning&) { return value(); }
};

template<>
struct DataType< ::dg_msgs::ChannelAligning > {
  static const char* value()
  {
    return "dg_msgs/ChannelAligning";
  }

  static const char* value(const ::dg_msgs::ChannelAligning&) { return value(); }
};


// service_traits::MD5Sum< ::dg_msgs::ChannelAligningRequest> should match
// service_traits::MD5Sum< ::dg_msgs::ChannelAligning >
template<>
struct MD5Sum< ::dg_msgs::ChannelAligningRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dg_msgs::ChannelAligning >::value();
  }
  static const char* value(const ::dg_msgs::ChannelAligningRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dg_msgs::ChannelAligningRequest> should match
// service_traits::DataType< ::dg_msgs::ChannelAligning >
template<>
struct DataType< ::dg_msgs::ChannelAligningRequest>
{
  static const char* value()
  {
    return DataType< ::dg_msgs::ChannelAligning >::value();
  }
  static const char* value(const ::dg_msgs::ChannelAligningRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dg_msgs::ChannelAligningResponse> should match
// service_traits::MD5Sum< ::dg_msgs::ChannelAligning >
template<>
struct MD5Sum< ::dg_msgs::ChannelAligningResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dg_msgs::ChannelAligning >::value();
  }
  static const char* value(const ::dg_msgs::ChannelAligningResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dg_msgs::ChannelAligningResponse> should match
// service_traits::DataType< ::dg_msgs::ChannelAligning >
template<>
struct DataType< ::dg_msgs::ChannelAligningResponse>
{
  static const char* value()
  {
    return DataType< ::dg_msgs::ChannelAligning >::value();
  }
  static const char* value(const ::dg_msgs::ChannelAligningResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DG_MSGS_MESSAGE_CHANNELALIGNING_H
