// Generated by gencpp from file dg_msgs/GetBollardState.msg
// DO NOT EDIT!


#ifndef DG_MSGS_MESSAGE_GETBOLLARDSTATE_H
#define DG_MSGS_MESSAGE_GETBOLLARDSTATE_H

#include <ros/service_traits.h>


#include <dg_msgs/GetBollardStateRequest.h>
#include <dg_msgs/GetBollardStateResponse.h>


namespace dg_msgs
{

struct GetBollardState
{

typedef GetBollardStateRequest Request;
typedef GetBollardStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetBollardState
} // namespace dg_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dg_msgs::GetBollardState > {
  static const char* value()
  {
    return "b8d36c8ac70f1a2e4bd8359afad61cf1";
  }

  static const char* value(const ::dg_msgs::GetBollardState&) { return value(); }
};

template<>
struct DataType< ::dg_msgs::GetBollardState > {
  static const char* value()
  {
    return "dg_msgs/GetBollardState";
  }

  static const char* value(const ::dg_msgs::GetBollardState&) { return value(); }
};


// service_traits::MD5Sum< ::dg_msgs::GetBollardStateRequest> should match
// service_traits::MD5Sum< ::dg_msgs::GetBollardState >
template<>
struct MD5Sum< ::dg_msgs::GetBollardStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dg_msgs::GetBollardState >::value();
  }
  static const char* value(const ::dg_msgs::GetBollardStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dg_msgs::GetBollardStateRequest> should match
// service_traits::DataType< ::dg_msgs::GetBollardState >
template<>
struct DataType< ::dg_msgs::GetBollardStateRequest>
{
  static const char* value()
  {
    return DataType< ::dg_msgs::GetBollardState >::value();
  }
  static const char* value(const ::dg_msgs::GetBollardStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dg_msgs::GetBollardStateResponse> should match
// service_traits::MD5Sum< ::dg_msgs::GetBollardState >
template<>
struct MD5Sum< ::dg_msgs::GetBollardStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dg_msgs::GetBollardState >::value();
  }
  static const char* value(const ::dg_msgs::GetBollardStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dg_msgs::GetBollardStateResponse> should match
// service_traits::DataType< ::dg_msgs::GetBollardState >
template<>
struct DataType< ::dg_msgs::GetBollardStateResponse>
{
  static const char* value()
  {
    return DataType< ::dg_msgs::GetBollardState >::value();
  }
  static const char* value(const ::dg_msgs::GetBollardStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DG_MSGS_MESSAGE_GETBOLLARDSTATE_H
