// Generated by gencpp from file dg_msgs/Interploate.msg
// DO NOT EDIT!


#ifndef DG_MSGS_MESSAGE_INTERPLOATE_H
#define DG_MSGS_MESSAGE_INTERPLOATE_H

#include <ros/service_traits.h>


#include <dg_msgs/InterploateRequest.h>
#include <dg_msgs/InterploateResponse.h>


namespace dg_msgs
{

struct Interploate
{

typedef InterploateRequest Request;
typedef InterploateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Interploate
} // namespace dg_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dg_msgs::Interploate > {
  static const char* value()
  {
    return "20ebdb9296a7b10c1ea97741e338b7bb";
  }

  static const char* value(const ::dg_msgs::Interploate&) { return value(); }
};

template<>
struct DataType< ::dg_msgs::Interploate > {
  static const char* value()
  {
    return "dg_msgs/Interploate";
  }

  static const char* value(const ::dg_msgs::Interploate&) { return value(); }
};


// service_traits::MD5Sum< ::dg_msgs::InterploateRequest> should match
// service_traits::MD5Sum< ::dg_msgs::Interploate >
template<>
struct MD5Sum< ::dg_msgs::InterploateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dg_msgs::Interploate >::value();
  }
  static const char* value(const ::dg_msgs::InterploateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dg_msgs::InterploateRequest> should match
// service_traits::DataType< ::dg_msgs::Interploate >
template<>
struct DataType< ::dg_msgs::InterploateRequest>
{
  static const char* value()
  {
    return DataType< ::dg_msgs::Interploate >::value();
  }
  static const char* value(const ::dg_msgs::InterploateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dg_msgs::InterploateResponse> should match
// service_traits::MD5Sum< ::dg_msgs::Interploate >
template<>
struct MD5Sum< ::dg_msgs::InterploateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dg_msgs::Interploate >::value();
  }
  static const char* value(const ::dg_msgs::InterploateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dg_msgs::InterploateResponse> should match
// service_traits::DataType< ::dg_msgs::Interploate >
template<>
struct DataType< ::dg_msgs::InterploateResponse>
{
  static const char* value()
  {
    return DataType< ::dg_msgs::Interploate >::value();
  }
  static const char* value(const ::dg_msgs::InterploateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DG_MSGS_MESSAGE_INTERPLOATE_H
