// Generated by gencpp from file dg_msgs/LiftkitUpDownResponse.msg
// DO NOT EDIT!


#ifndef DG_MSGS_MESSAGE_LIFTKITUPDOWNRESPONSE_H
#define DG_MSGS_MESSAGE_LIFTKITUPDOWNRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dg_msgs
{
template <class ContainerAllocator>
struct LiftkitUpDownResponse_
{
  typedef LiftkitUpDownResponse_<ContainerAllocator> Type;

  LiftkitUpDownResponse_()
    : result(0)
    , height(0.0)  {
    }
  LiftkitUpDownResponse_(const ContainerAllocator& _alloc)
    : result(0)
    , height(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _result_type;
  _result_type result;

   typedef float _height_type;
  _height_type height;





  typedef boost::shared_ptr< ::dg_msgs::LiftkitUpDownResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dg_msgs::LiftkitUpDownResponse_<ContainerAllocator> const> ConstPtr;

}; // struct LiftkitUpDownResponse_

typedef ::dg_msgs::LiftkitUpDownResponse_<std::allocator<void> > LiftkitUpDownResponse;

typedef boost::shared_ptr< ::dg_msgs::LiftkitUpDownResponse > LiftkitUpDownResponsePtr;
typedef boost::shared_ptr< ::dg_msgs::LiftkitUpDownResponse const> LiftkitUpDownResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dg_msgs::LiftkitUpDownResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dg_msgs::LiftkitUpDownResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dg_msgs::LiftkitUpDownResponse_<ContainerAllocator1> & lhs, const ::dg_msgs::LiftkitUpDownResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result &&
    lhs.height == rhs.height;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dg_msgs::LiftkitUpDownResponse_<ContainerAllocator1> & lhs, const ::dg_msgs::LiftkitUpDownResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dg_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::dg_msgs::LiftkitUpDownResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dg_msgs::LiftkitUpDownResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dg_msgs::LiftkitUpDownResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dg_msgs::LiftkitUpDownResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dg_msgs::LiftkitUpDownResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dg_msgs::LiftkitUpDownResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dg_msgs::LiftkitUpDownResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4bee10a76df103ce680ba5e319093346";
  }

  static const char* value(const ::dg_msgs::LiftkitUpDownResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4bee10a76df103ceULL;
  static const uint64_t static_value2 = 0x680ba5e319093346ULL;
};

template<class ContainerAllocator>
struct DataType< ::dg_msgs::LiftkitUpDownResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dg_msgs/LiftkitUpDownResponse";
  }

  static const char* value(const ::dg_msgs::LiftkitUpDownResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dg_msgs::LiftkitUpDownResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 result\n"
"float32 height          # 升降柱当前的高度\n"
"\n"
;
  }

  static const char* value(const ::dg_msgs::LiftkitUpDownResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dg_msgs::LiftkitUpDownResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
      stream.next(m.height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LiftkitUpDownResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dg_msgs::LiftkitUpDownResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dg_msgs::LiftkitUpDownResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int32_t>::stream(s, indent + "  ", v.result);
    s << indent << "height: ";
    Printer<float>::stream(s, indent + "  ", v.height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DG_MSGS_MESSAGE_LIFTKITUPDOWNRESPONSE_H
