// Generated by gencpp from file dg_msgs/LiftkitUpDownRequest.msg
// DO NOT EDIT!


#ifndef DG_MSGS_MESSAGE_LIFTKITUPDOWNREQUEST_H
#define DG_MSGS_MESSAGE_LIFTKITUPDOWNREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dg_msgs
{
template <class ContainerAllocator>
struct LiftkitUpDownRequest_
{
  typedef LiftkitUpDownRequest_<ContainerAllocator> Type;

  LiftkitUpDownRequest_()
    : number()
    , operation(0)  {
    }
  LiftkitUpDownRequest_(const ContainerAllocator& _alloc)
    : number(_alloc)
    , operation(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _number_type;
  _number_type number;

   typedef int32_t _operation_type;
  _operation_type operation;





  typedef boost::shared_ptr< ::dg_msgs::LiftkitUpDownRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dg_msgs::LiftkitUpDownRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LiftkitUpDownRequest_

typedef ::dg_msgs::LiftkitUpDownRequest_<std::allocator<void> > LiftkitUpDownRequest;

typedef boost::shared_ptr< ::dg_msgs::LiftkitUpDownRequest > LiftkitUpDownRequestPtr;
typedef boost::shared_ptr< ::dg_msgs::LiftkitUpDownRequest const> LiftkitUpDownRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dg_msgs::LiftkitUpDownRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dg_msgs::LiftkitUpDownRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dg_msgs::LiftkitUpDownRequest_<ContainerAllocator1> & lhs, const ::dg_msgs::LiftkitUpDownRequest_<ContainerAllocator2> & rhs)
{
  return lhs.number == rhs.number &&
    lhs.operation == rhs.operation;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dg_msgs::LiftkitUpDownRequest_<ContainerAllocator1> & lhs, const ::dg_msgs::LiftkitUpDownRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dg_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::dg_msgs::LiftkitUpDownRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dg_msgs::LiftkitUpDownRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dg_msgs::LiftkitUpDownRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dg_msgs::LiftkitUpDownRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dg_msgs::LiftkitUpDownRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dg_msgs::LiftkitUpDownRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dg_msgs::LiftkitUpDownRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3b007819b02bbb1523509a91db0b1b6d";
  }

  static const char* value(const ::dg_msgs::LiftkitUpDownRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3b007819b02bbb15ULL;
  static const uint64_t static_value2 = 0x23509a91db0b1b6dULL;
};

template<class ContainerAllocator>
struct DataType< ::dg_msgs::LiftkitUpDownRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dg_msgs/LiftkitUpDownRequest";
  }

  static const char* value(const ::dg_msgs::LiftkitUpDownRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dg_msgs::LiftkitUpDownRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string number       # 设备编码\n"
"int32 operation     # 1：上升； 2：下降； 3：停止\n"
;
  }

  static const char* value(const ::dg_msgs::LiftkitUpDownRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dg_msgs::LiftkitUpDownRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.number);
      stream.next(m.operation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LiftkitUpDownRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dg_msgs::LiftkitUpDownRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dg_msgs::LiftkitUpDownRequest_<ContainerAllocator>& v)
  {
    s << indent << "number: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.number);
    s << indent << "operation: ";
    Printer<int32_t>::stream(s, indent + "  ", v.operation);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DG_MSGS_MESSAGE_LIFTKITUPDOWNREQUEST_H
