// Generated by gencpp from file dg_msgs/PcdRegistrationResponse.msg
// DO NOT EDIT!


#ifndef DG_MSGS_MESSAGE_PCDREGISTRATIONRESPONSE_H
#define DG_MSGS_MESSAGE_PCDREGISTRATIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Transform.h>
#include <dg_msgs/UniversalStateInfo.h>

namespace dg_msgs
{
template <class ContainerAllocator>
struct PcdRegistrationResponse_
{
  typedef PcdRegistrationResponse_<ContainerAllocator> Type;

  PcdRegistrationResponse_()
    : transform()
    , state_info()  {
    }
  PcdRegistrationResponse_(const ContainerAllocator& _alloc)
    : transform(_alloc)
    , state_info(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Transform_<ContainerAllocator>  _transform_type;
  _transform_type transform;

   typedef  ::dg_msgs::UniversalStateInfo_<ContainerAllocator>  _state_info_type;
  _state_info_type state_info;





  typedef boost::shared_ptr< ::dg_msgs::PcdRegistrationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dg_msgs::PcdRegistrationResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PcdRegistrationResponse_

typedef ::dg_msgs::PcdRegistrationResponse_<std::allocator<void> > PcdRegistrationResponse;

typedef boost::shared_ptr< ::dg_msgs::PcdRegistrationResponse > PcdRegistrationResponsePtr;
typedef boost::shared_ptr< ::dg_msgs::PcdRegistrationResponse const> PcdRegistrationResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dg_msgs::PcdRegistrationResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dg_msgs::PcdRegistrationResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dg_msgs::PcdRegistrationResponse_<ContainerAllocator1> & lhs, const ::dg_msgs::PcdRegistrationResponse_<ContainerAllocator2> & rhs)
{
  return lhs.transform == rhs.transform &&
    lhs.state_info == rhs.state_info;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dg_msgs::PcdRegistrationResponse_<ContainerAllocator1> & lhs, const ::dg_msgs::PcdRegistrationResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dg_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::dg_msgs::PcdRegistrationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dg_msgs::PcdRegistrationResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dg_msgs::PcdRegistrationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dg_msgs::PcdRegistrationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dg_msgs::PcdRegistrationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dg_msgs::PcdRegistrationResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dg_msgs::PcdRegistrationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9774c230801f2006a1a918dac5bfc005";
  }

  static const char* value(const ::dg_msgs::PcdRegistrationResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9774c230801f2006ULL;
  static const uint64_t static_value2 = 0xa1a918dac5bfc005ULL;
};

template<class ContainerAllocator>
struct DataType< ::dg_msgs::PcdRegistrationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dg_msgs/PcdRegistrationResponse";
  }

  static const char* value(const ::dg_msgs::PcdRegistrationResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dg_msgs::PcdRegistrationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# bool result_registration\n"
"# string status_info\n"
"geometry_msgs/Transform transform\n"
"UniversalStateInfo  state_info # state_index: 0 配准成功 1 配准失败 2 读取target点云文件失败 3 读取source点云文件失败 4 从激光雷达获取点云失败 5 从相机获取点云失败\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Transform\n"
"# This represents the transform between two coordinate frames in free space.\n"
"\n"
"Vector3 translation\n"
"Quaternion rotation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: dg_msgs/UniversalStateInfo\n"
"int32 state_index   # 状态索引值：统一0是正常，其他数字自定义\n"
"string node_name    # 当前节点名\n"
"string state_msgs   # 附加信息，相当于additional_msgs\n"
;
  }

  static const char* value(const ::dg_msgs::PcdRegistrationResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dg_msgs::PcdRegistrationResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.transform);
      stream.next(m.state_info);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PcdRegistrationResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dg_msgs::PcdRegistrationResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dg_msgs::PcdRegistrationResponse_<ContainerAllocator>& v)
  {
    s << indent << "transform: ";
    s << std::endl;
    Printer< ::geometry_msgs::Transform_<ContainerAllocator> >::stream(s, indent + "  ", v.transform);
    s << indent << "state_info: ";
    s << std::endl;
    Printer< ::dg_msgs::UniversalStateInfo_<ContainerAllocator> >::stream(s, indent + "  ", v.state_info);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DG_MSGS_MESSAGE_PCDREGISTRATIONRESPONSE_H
