// Generated by gencpp from file dg_msgs/RobotArmAcqReadyResponse.msg
// DO NOT EDIT!


#ifndef DG_MSGS_MESSAGE_ROBOTARMACQREADYRESPONSE_H
#define DG_MSGS_MESSAGE_ROBOTARMACQREADYRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>
#include <dg_msgs/UniversalStateInfo.h>

namespace dg_msgs
{
template <class ContainerAllocator>
struct RobotArmAcqReadyResponse_
{
  typedef RobotArmAcqReadyResponse_<ContainerAllocator> Type;

  RobotArmAcqReadyResponse_()
    : correction_pose()
    , state_info()  {
    }
  RobotArmAcqReadyResponse_(const ContainerAllocator& _alloc)
    : correction_pose(_alloc)
    , state_info(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _correction_pose_type;
  _correction_pose_type correction_pose;

   typedef  ::dg_msgs::UniversalStateInfo_<ContainerAllocator>  _state_info_type;
  _state_info_type state_info;





  typedef boost::shared_ptr< ::dg_msgs::RobotArmAcqReadyResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dg_msgs::RobotArmAcqReadyResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RobotArmAcqReadyResponse_

typedef ::dg_msgs::RobotArmAcqReadyResponse_<std::allocator<void> > RobotArmAcqReadyResponse;

typedef boost::shared_ptr< ::dg_msgs::RobotArmAcqReadyResponse > RobotArmAcqReadyResponsePtr;
typedef boost::shared_ptr< ::dg_msgs::RobotArmAcqReadyResponse const> RobotArmAcqReadyResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dg_msgs::RobotArmAcqReadyResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dg_msgs::RobotArmAcqReadyResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dg_msgs::RobotArmAcqReadyResponse_<ContainerAllocator1> & lhs, const ::dg_msgs::RobotArmAcqReadyResponse_<ContainerAllocator2> & rhs)
{
  return lhs.correction_pose == rhs.correction_pose &&
    lhs.state_info == rhs.state_info;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dg_msgs::RobotArmAcqReadyResponse_<ContainerAllocator1> & lhs, const ::dg_msgs::RobotArmAcqReadyResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dg_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::dg_msgs::RobotArmAcqReadyResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dg_msgs::RobotArmAcqReadyResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dg_msgs::RobotArmAcqReadyResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dg_msgs::RobotArmAcqReadyResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dg_msgs::RobotArmAcqReadyResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dg_msgs::RobotArmAcqReadyResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dg_msgs::RobotArmAcqReadyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e3a35aadd4af7a6bf19580a53899f34f";
  }

  static const char* value(const ::dg_msgs::RobotArmAcqReadyResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe3a35aadd4af7a6bULL;
  static const uint64_t static_value2 = 0xf19580a53899f34fULL;
};

template<class ContainerAllocator>
struct DataType< ::dg_msgs::RobotArmAcqReadyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dg_msgs/RobotArmAcqReadyResponse";
  }

  static const char* value(const ::dg_msgs::RobotArmAcqReadyResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dg_msgs::RobotArmAcqReadyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose  correction_pose              # 反馈给中心节点停车点位的位移偏差(用于里程计校准)\n"
"UniversalStateInfo  state_info                   # error 1 机械臂初始位置错误；2 坑道模型加载错误；3 转向架模型加载失败；\n"
"                                                 # 4 配准服务调用失败；5 机械臂运动失败；6 机械臂规划到纠偏点位失败；\n"
"                                                 # 7 外部轴运动失败；8 终止指令返回；\n"
"                                                 # warning  9 暂停指令返回；\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: dg_msgs/UniversalStateInfo\n"
"int32 state_index   # 状态索引值：统一0是正常，其他数字自定义\n"
"string node_name    # 当前节点名\n"
"string state_msgs   # 附加信息，相当于additional_msgs\n"
;
  }

  static const char* value(const ::dg_msgs::RobotArmAcqReadyResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dg_msgs::RobotArmAcqReadyResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.correction_pose);
      stream.next(m.state_info);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotArmAcqReadyResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dg_msgs::RobotArmAcqReadyResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dg_msgs::RobotArmAcqReadyResponse_<ContainerAllocator>& v)
  {
    s << indent << "correction_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.correction_pose);
    s << indent << "state_info: ";
    s << std::endl;
    Printer< ::dg_msgs::UniversalStateInfo_<ContainerAllocator> >::stream(s, indent + "  ", v.state_info);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DG_MSGS_MESSAGE_ROBOTARMACQREADYRESPONSE_H
