// Generated by gencpp from file dg_msgs/RobotArmHomeCheckResponse.msg
// DO NOT EDIT!


#ifndef DG_MSGS_MESSAGE_ROBOTARMHOMECHECKRESPONSE_H
#define DG_MSGS_MESSAGE_ROBOTARMHOMECHECKRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dg_msgs
{
template <class ContainerAllocator>
struct RobotArmHomeCheckResponse_
{
  typedef RobotArmHomeCheckResponse_<ContainerAllocator> Type;

  RobotArmHomeCheckResponse_()
    : ret(0)  {
    }
  RobotArmHomeCheckResponse_(const ContainerAllocator& _alloc)
    : ret(0)  {
  (void)_alloc;
    }



   typedef int32_t _ret_type;
  _ret_type ret;





  typedef boost::shared_ptr< ::dg_msgs::RobotArmHomeCheckResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dg_msgs::RobotArmHomeCheckResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RobotArmHomeCheckResponse_

typedef ::dg_msgs::RobotArmHomeCheckResponse_<std::allocator<void> > RobotArmHomeCheckResponse;

typedef boost::shared_ptr< ::dg_msgs::RobotArmHomeCheckResponse > RobotArmHomeCheckResponsePtr;
typedef boost::shared_ptr< ::dg_msgs::RobotArmHomeCheckResponse const> RobotArmHomeCheckResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dg_msgs::RobotArmHomeCheckResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dg_msgs::RobotArmHomeCheckResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dg_msgs::RobotArmHomeCheckResponse_<ContainerAllocator1> & lhs, const ::dg_msgs::RobotArmHomeCheckResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ret == rhs.ret;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dg_msgs::RobotArmHomeCheckResponse_<ContainerAllocator1> & lhs, const ::dg_msgs::RobotArmHomeCheckResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dg_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::dg_msgs::RobotArmHomeCheckResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dg_msgs::RobotArmHomeCheckResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dg_msgs::RobotArmHomeCheckResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dg_msgs::RobotArmHomeCheckResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dg_msgs::RobotArmHomeCheckResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dg_msgs::RobotArmHomeCheckResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dg_msgs::RobotArmHomeCheckResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3bd113e2f12c9c571d32a0bd71d59b8d";
  }

  static const char* value(const ::dg_msgs::RobotArmHomeCheckResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3bd113e2f12c9c57ULL;
  static const uint64_t static_value2 = 0x1d32a0bd71d59b8dULL;
};

template<class ContainerAllocator>
struct DataType< ::dg_msgs::RobotArmHomeCheckResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dg_msgs/RobotArmHomeCheckResponse";
  }

  static const char* value(const ::dg_msgs::RobotArmHomeCheckResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dg_msgs::RobotArmHomeCheckResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 ret          #0表示在Home初始位置\n"
;
  }

  static const char* value(const ::dg_msgs::RobotArmHomeCheckResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dg_msgs::RobotArmHomeCheckResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ret);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotArmHomeCheckResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dg_msgs::RobotArmHomeCheckResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dg_msgs::RobotArmHomeCheckResponse_<ContainerAllocator>& v)
  {
    s << indent << "ret: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ret);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DG_MSGS_MESSAGE_ROBOTARMHOMECHECKRESPONSE_H
