// Generated by gencpp from file dg_msgs/SafeDistanceSetRequest.msg
// DO NOT EDIT!


#ifndef DG_MSGS_MESSAGE_SAFEDISTANCESETREQUEST_H
#define DG_MSGS_MESSAGE_SAFEDISTANCESETREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dg_msgs
{
template <class ContainerAllocator>
struct SafeDistanceSetRequest_
{
  typedef SafeDistanceSetRequest_<ContainerAllocator> Type;

  SafeDistanceSetRequest_()
    : number()
    , dist(0.0)  {
    }
  SafeDistanceSetRequest_(const ContainerAllocator& _alloc)
    : number(_alloc)
    , dist(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _number_type;
  _number_type number;

   typedef float _dist_type;
  _dist_type dist;





  typedef boost::shared_ptr< ::dg_msgs::SafeDistanceSetRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dg_msgs::SafeDistanceSetRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SafeDistanceSetRequest_

typedef ::dg_msgs::SafeDistanceSetRequest_<std::allocator<void> > SafeDistanceSetRequest;

typedef boost::shared_ptr< ::dg_msgs::SafeDistanceSetRequest > SafeDistanceSetRequestPtr;
typedef boost::shared_ptr< ::dg_msgs::SafeDistanceSetRequest const> SafeDistanceSetRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dg_msgs::SafeDistanceSetRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dg_msgs::SafeDistanceSetRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dg_msgs::SafeDistanceSetRequest_<ContainerAllocator1> & lhs, const ::dg_msgs::SafeDistanceSetRequest_<ContainerAllocator2> & rhs)
{
  return lhs.number == rhs.number &&
    lhs.dist == rhs.dist;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dg_msgs::SafeDistanceSetRequest_<ContainerAllocator1> & lhs, const ::dg_msgs::SafeDistanceSetRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dg_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::dg_msgs::SafeDistanceSetRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dg_msgs::SafeDistanceSetRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dg_msgs::SafeDistanceSetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dg_msgs::SafeDistanceSetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dg_msgs::SafeDistanceSetRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dg_msgs::SafeDistanceSetRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dg_msgs::SafeDistanceSetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5c6e3bc8cc5607d3fc34fcdc38d64819";
  }

  static const char* value(const ::dg_msgs::SafeDistanceSetRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5c6e3bc8cc5607d3ULL;
  static const uint64_t static_value2 = 0xfc34fcdc38d64819ULL;
};

template<class ContainerAllocator>
struct DataType< ::dg_msgs::SafeDistanceSetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dg_msgs/SafeDistanceSetRequest";
  }

  static const char* value(const ::dg_msgs::SafeDistanceSetRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dg_msgs::SafeDistanceSetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string number       # 设备编码\n"
"float32 dist       # 机械臂和碰撞物的安全距离，单位米\n"
;
  }

  static const char* value(const ::dg_msgs::SafeDistanceSetRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dg_msgs::SafeDistanceSetRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.number);
      stream.next(m.dist);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SafeDistanceSetRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dg_msgs::SafeDistanceSetRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dg_msgs::SafeDistanceSetRequest_<ContainerAllocator>& v)
  {
    s << indent << "number: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.number);
    s << indent << "dist: ";
    Printer<float>::stream(s, indent + "  ", v.dist);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DG_MSGS_MESSAGE_SAFEDISTANCESETREQUEST_H
