// Generated by gencpp from file dg_msgs/TakeAPictureResult.msg
// DO NOT EDIT!


#ifndef DG_MSGS_MESSAGE_TAKEAPICTURERESULT_H
#define DG_MSGS_MESSAGE_TAKEAPICTURERESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <dg_msgs/UniversalStateInfo.h>

namespace dg_msgs
{
template <class ContainerAllocator>
struct TakeAPictureResult_
{
  typedef TakeAPictureResult_<ContainerAllocator> Type;

  TakeAPictureResult_()
    : pointCloud()
    , rgb()
    , depth()
    , state_info()  {
    }
  TakeAPictureResult_(const ContainerAllocator& _alloc)
    : pointCloud(_alloc)
    , rgb(_alloc)
    , depth(_alloc)
    , state_info(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _pointCloud_type;
  _pointCloud_type pointCloud;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _rgb_type;
  _rgb_type rgb;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _depth_type;
  _depth_type depth;

   typedef  ::dg_msgs::UniversalStateInfo_<ContainerAllocator>  _state_info_type;
  _state_info_type state_info;





  typedef boost::shared_ptr< ::dg_msgs::TakeAPictureResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dg_msgs::TakeAPictureResult_<ContainerAllocator> const> ConstPtr;

}; // struct TakeAPictureResult_

typedef ::dg_msgs::TakeAPictureResult_<std::allocator<void> > TakeAPictureResult;

typedef boost::shared_ptr< ::dg_msgs::TakeAPictureResult > TakeAPictureResultPtr;
typedef boost::shared_ptr< ::dg_msgs::TakeAPictureResult const> TakeAPictureResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dg_msgs::TakeAPictureResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dg_msgs::TakeAPictureResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dg_msgs::TakeAPictureResult_<ContainerAllocator1> & lhs, const ::dg_msgs::TakeAPictureResult_<ContainerAllocator2> & rhs)
{
  return lhs.pointCloud == rhs.pointCloud &&
    lhs.rgb == rhs.rgb &&
    lhs.depth == rhs.depth &&
    lhs.state_info == rhs.state_info;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dg_msgs::TakeAPictureResult_<ContainerAllocator1> & lhs, const ::dg_msgs::TakeAPictureResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dg_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::dg_msgs::TakeAPictureResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dg_msgs::TakeAPictureResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dg_msgs::TakeAPictureResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dg_msgs::TakeAPictureResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dg_msgs::TakeAPictureResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dg_msgs::TakeAPictureResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dg_msgs::TakeAPictureResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "43a9f96505994e95f9f117bf4737a0c7";
  }

  static const char* value(const ::dg_msgs::TakeAPictureResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x43a9f96505994e95ULL;
  static const uint64_t static_value2 = 0xf9f117bf4737a0c7ULL;
};

template<class ContainerAllocator>
struct DataType< ::dg_msgs::TakeAPictureResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dg_msgs/TakeAPictureResult";
  }

  static const char* value(const ::dg_msgs::TakeAPictureResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dg_msgs::TakeAPictureResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result definition\n"
"string pointCloud\n"
"string rgb\n"
"string depth\n"
"UniversalStateInfo  state_info\n"
"  \n"
"# 0 表示成功；\n"
"# error: 1 表示点云存储失败\n"
"#        2 表示rgb图像存储失败\n"
"#        3 表示深度图存储失败\n"
"\n"
"================================================================================\n"
"MSG: dg_msgs/UniversalStateInfo\n"
"int32 state_index   # 状态索引值：统一0是正常，其他数字自定义\n"
"string node_name    # 当前节点名\n"
"string state_msgs   # 附加信息，相当于additional_msgs\n"
;
  }

  static const char* value(const ::dg_msgs::TakeAPictureResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dg_msgs::TakeAPictureResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pointCloud);
      stream.next(m.rgb);
      stream.next(m.depth);
      stream.next(m.state_info);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TakeAPictureResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dg_msgs::TakeAPictureResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dg_msgs::TakeAPictureResult_<ContainerAllocator>& v)
  {
    s << indent << "pointCloud: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.pointCloud);
    s << indent << "rgb: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.rgb);
    s << indent << "depth: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.depth);
    s << indent << "state_info: ";
    s << std::endl;
    Printer< ::dg_msgs::UniversalStateInfo_<ContainerAllocator> >::stream(s, indent + "  ", v.state_info);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DG_MSGS_MESSAGE_TAKEAPICTURERESULT_H
