// Generated by gencpp from file dg_msgs/TakeAPointCloud.msg
// DO NOT EDIT!


#ifndef DG_MSGS_MESSAGE_TAKEAPOINTCLOUD_H
#define DG_MSGS_MESSAGE_TAKEAPOINTCLOUD_H

#include <ros/service_traits.h>


#include <dg_msgs/TakeAPointCloudRequest.h>
#include <dg_msgs/TakeAPointCloudResponse.h>


namespace dg_msgs
{

struct TakeAPointCloud
{

typedef TakeAPointCloudRequest Request;
typedef TakeAPointCloudResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TakeAPointCloud
} // namespace dg_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dg_msgs::TakeAPointCloud > {
  static const char* value()
  {
    return "62cbe1cfe333a66132a02f178e9a8274";
  }

  static const char* value(const ::dg_msgs::TakeAPointCloud&) { return value(); }
};

template<>
struct DataType< ::dg_msgs::TakeAPointCloud > {
  static const char* value()
  {
    return "dg_msgs/TakeAPointCloud";
  }

  static const char* value(const ::dg_msgs::TakeAPointCloud&) { return value(); }
};


// service_traits::MD5Sum< ::dg_msgs::TakeAPointCloudRequest> should match
// service_traits::MD5Sum< ::dg_msgs::TakeAPointCloud >
template<>
struct MD5Sum< ::dg_msgs::TakeAPointCloudRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dg_msgs::TakeAPointCloud >::value();
  }
  static const char* value(const ::dg_msgs::TakeAPointCloudRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dg_msgs::TakeAPointCloudRequest> should match
// service_traits::DataType< ::dg_msgs::TakeAPointCloud >
template<>
struct DataType< ::dg_msgs::TakeAPointCloudRequest>
{
  static const char* value()
  {
    return DataType< ::dg_msgs::TakeAPointCloud >::value();
  }
  static const char* value(const ::dg_msgs::TakeAPointCloudRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dg_msgs::TakeAPointCloudResponse> should match
// service_traits::MD5Sum< ::dg_msgs::TakeAPointCloud >
template<>
struct MD5Sum< ::dg_msgs::TakeAPointCloudResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dg_msgs::TakeAPointCloud >::value();
  }
  static const char* value(const ::dg_msgs::TakeAPointCloudResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dg_msgs::TakeAPointCloudResponse> should match
// service_traits::DataType< ::dg_msgs::TakeAPointCloud >
template<>
struct DataType< ::dg_msgs::TakeAPointCloudResponse>
{
  static const char* value()
  {
    return DataType< ::dg_msgs::TakeAPointCloud >::value();
  }
  static const char* value(const ::dg_msgs::TakeAPointCloudResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DG_MSGS_MESSAGE_TAKEAPOINTCLOUD_H
