// Generated by gencpp from file dg_msgs/TeachingRegframe.msg
// DO NOT EDIT!


#ifndef DG_MSGS_MESSAGE_TEACHINGREGFRAME_H
#define DG_MSGS_MESSAGE_TEACHINGREGFRAME_H

#include <ros/service_traits.h>


#include <dg_msgs/TeachingRegframeRequest.h>
#include <dg_msgs/TeachingRegframeResponse.h>


namespace dg_msgs
{

struct TeachingRegframe
{

typedef TeachingRegframeRequest Request;
typedef TeachingRegframeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TeachingRegframe
} // namespace dg_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dg_msgs::TeachingRegframe > {
  static const char* value()
  {
    return "82733c39cc3dc283e1ac8112691de480";
  }

  static const char* value(const ::dg_msgs::TeachingRegframe&) { return value(); }
};

template<>
struct DataType< ::dg_msgs::TeachingRegframe > {
  static const char* value()
  {
    return "dg_msgs/TeachingRegframe";
  }

  static const char* value(const ::dg_msgs::TeachingRegframe&) { return value(); }
};


// service_traits::MD5Sum< ::dg_msgs::TeachingRegframeRequest> should match
// service_traits::MD5Sum< ::dg_msgs::TeachingRegframe >
template<>
struct MD5Sum< ::dg_msgs::TeachingRegframeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dg_msgs::TeachingRegframe >::value();
  }
  static const char* value(const ::dg_msgs::TeachingRegframeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dg_msgs::TeachingRegframeRequest> should match
// service_traits::DataType< ::dg_msgs::TeachingRegframe >
template<>
struct DataType< ::dg_msgs::TeachingRegframeRequest>
{
  static const char* value()
  {
    return DataType< ::dg_msgs::TeachingRegframe >::value();
  }
  static const char* value(const ::dg_msgs::TeachingRegframeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dg_msgs::TeachingRegframeResponse> should match
// service_traits::MD5Sum< ::dg_msgs::TeachingRegframe >
template<>
struct MD5Sum< ::dg_msgs::TeachingRegframeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dg_msgs::TeachingRegframe >::value();
  }
  static const char* value(const ::dg_msgs::TeachingRegframeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dg_msgs::TeachingRegframeResponse> should match
// service_traits::DataType< ::dg_msgs::TeachingRegframe >
template<>
struct DataType< ::dg_msgs::TeachingRegframeResponse>
{
  static const char* value()
  {
    return DataType< ::dg_msgs::TeachingRegframe >::value();
  }
  static const char* value(const ::dg_msgs::TeachingRegframeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DG_MSGS_MESSAGE_TEACHINGREGFRAME_H
