// Generated by gencpp from file dg_msgs/TrainStopLocation.msg
// DO NOT EDIT!


#ifndef DG_MSGS_MESSAGE_TRAINSTOPLOCATION_H
#define DG_MSGS_MESSAGE_TRAINSTOPLOCATION_H

#include <ros/service_traits.h>


#include <dg_msgs/TrainStopLocationRequest.h>
#include <dg_msgs/TrainStopLocationResponse.h>


namespace dg_msgs
{

struct TrainStopLocation
{

typedef TrainStopLocationRequest Request;
typedef TrainStopLocationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TrainStopLocation
} // namespace dg_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dg_msgs::TrainStopLocation > {
  static const char* value()
  {
    return "1bfaf8027cbdae005d41220561672628";
  }

  static const char* value(const ::dg_msgs::TrainStopLocation&) { return value(); }
};

template<>
struct DataType< ::dg_msgs::TrainStopLocation > {
  static const char* value()
  {
    return "dg_msgs/TrainStopLocation";
  }

  static const char* value(const ::dg_msgs::TrainStopLocation&) { return value(); }
};


// service_traits::MD5Sum< ::dg_msgs::TrainStopLocationRequest> should match
// service_traits::MD5Sum< ::dg_msgs::TrainStopLocation >
template<>
struct MD5Sum< ::dg_msgs::TrainStopLocationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dg_msgs::TrainStopLocation >::value();
  }
  static const char* value(const ::dg_msgs::TrainStopLocationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dg_msgs::TrainStopLocationRequest> should match
// service_traits::DataType< ::dg_msgs::TrainStopLocation >
template<>
struct DataType< ::dg_msgs::TrainStopLocationRequest>
{
  static const char* value()
  {
    return DataType< ::dg_msgs::TrainStopLocation >::value();
  }
  static const char* value(const ::dg_msgs::TrainStopLocationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dg_msgs::TrainStopLocationResponse> should match
// service_traits::MD5Sum< ::dg_msgs::TrainStopLocation >
template<>
struct MD5Sum< ::dg_msgs::TrainStopLocationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dg_msgs::TrainStopLocation >::value();
  }
  static const char* value(const ::dg_msgs::TrainStopLocationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dg_msgs::TrainStopLocationResponse> should match
// service_traits::DataType< ::dg_msgs::TrainStopLocation >
template<>
struct DataType< ::dg_msgs::TrainStopLocationResponse>
{
  static const char* value()
  {
    return DataType< ::dg_msgs::TrainStopLocation >::value();
  }
  static const char* value(const ::dg_msgs::TrainStopLocationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DG_MSGS_MESSAGE_TRAINSTOPLOCATION_H
