// Generated by gencpp from file dg_msgs/XGGoToCharge.msg
// DO NOT EDIT!


#ifndef DG_MSGS_MESSAGE_XGGOTOCHARGE_H
#define DG_MSGS_MESSAGE_XGGOTOCHARGE_H

#include <ros/service_traits.h>


#include <dg_msgs/XGGoToChargeRequest.h>
#include <dg_msgs/XGGoToChargeResponse.h>


namespace dg_msgs
{

struct XGGoToCharge
{

typedef XGGoToChargeRequest Request;
typedef XGGoToChargeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct XGGoToCharge
} // namespace dg_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dg_msgs::XGGoToCharge > {
  static const char* value()
  {
    return "17a225b0388e872b5c33b08b315a6550";
  }

  static const char* value(const ::dg_msgs::XGGoToCharge&) { return value(); }
};

template<>
struct DataType< ::dg_msgs::XGGoToCharge > {
  static const char* value()
  {
    return "dg_msgs/XGGoToCharge";
  }

  static const char* value(const ::dg_msgs::XGGoToCharge&) { return value(); }
};


// service_traits::MD5Sum< ::dg_msgs::XGGoToChargeRequest> should match
// service_traits::MD5Sum< ::dg_msgs::XGGoToCharge >
template<>
struct MD5Sum< ::dg_msgs::XGGoToChargeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dg_msgs::XGGoToCharge >::value();
  }
  static const char* value(const ::dg_msgs::XGGoToChargeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dg_msgs::XGGoToChargeRequest> should match
// service_traits::DataType< ::dg_msgs::XGGoToCharge >
template<>
struct DataType< ::dg_msgs::XGGoToChargeRequest>
{
  static const char* value()
  {
    return DataType< ::dg_msgs::XGGoToCharge >::value();
  }
  static const char* value(const ::dg_msgs::XGGoToChargeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dg_msgs::XGGoToChargeResponse> should match
// service_traits::MD5Sum< ::dg_msgs::XGGoToCharge >
template<>
struct MD5Sum< ::dg_msgs::XGGoToChargeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dg_msgs::XGGoToCharge >::value();
  }
  static const char* value(const ::dg_msgs::XGGoToChargeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dg_msgs::XGGoToChargeResponse> should match
// service_traits::DataType< ::dg_msgs::XGGoToCharge >
template<>
struct DataType< ::dg_msgs::XGGoToChargeResponse>
{
  static const char* value()
  {
    return DataType< ::dg_msgs::XGGoToCharge >::value();
  }
  static const char* value(const ::dg_msgs::XGGoToChargeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DG_MSGS_MESSAGE_XGGOTOCHARGE_H
