// Generated by gencpp from file dg_msgs/XGPillerCenter.msg
// DO NOT EDIT!


#ifndef DG_MSGS_MESSAGE_XGPILLERCENTER_H
#define DG_MSGS_MESSAGE_XGPILLERCENTER_H

#include <ros/service_traits.h>


#include <dg_msgs/XGPillerCenterRequest.h>
#include <dg_msgs/XGPillerCenterResponse.h>


namespace dg_msgs
{

struct XGPillerCenter
{

typedef XGPillerCenterRequest Request;
typedef XGPillerCenterResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct XGPillerCenter
} // namespace dg_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dg_msgs::XGPillerCenter > {
  static const char* value()
  {
    return "44a8d4b0b3e7baca9bbc0e508470774d";
  }

  static const char* value(const ::dg_msgs::XGPillerCenter&) { return value(); }
};

template<>
struct DataType< ::dg_msgs::XGPillerCenter > {
  static const char* value()
  {
    return "dg_msgs/XGPillerCenter";
  }

  static const char* value(const ::dg_msgs::XGPillerCenter&) { return value(); }
};


// service_traits::MD5Sum< ::dg_msgs::XGPillerCenterRequest> should match
// service_traits::MD5Sum< ::dg_msgs::XGPillerCenter >
template<>
struct MD5Sum< ::dg_msgs::XGPillerCenterRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dg_msgs::XGPillerCenter >::value();
  }
  static const char* value(const ::dg_msgs::XGPillerCenterRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dg_msgs::XGPillerCenterRequest> should match
// service_traits::DataType< ::dg_msgs::XGPillerCenter >
template<>
struct DataType< ::dg_msgs::XGPillerCenterRequest>
{
  static const char* value()
  {
    return DataType< ::dg_msgs::XGPillerCenter >::value();
  }
  static const char* value(const ::dg_msgs::XGPillerCenterRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dg_msgs::XGPillerCenterResponse> should match
// service_traits::MD5Sum< ::dg_msgs::XGPillerCenter >
template<>
struct MD5Sum< ::dg_msgs::XGPillerCenterResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dg_msgs::XGPillerCenter >::value();
  }
  static const char* value(const ::dg_msgs::XGPillerCenterResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dg_msgs::XGPillerCenterResponse> should match
// service_traits::DataType< ::dg_msgs::XGPillerCenter >
template<>
struct DataType< ::dg_msgs::XGPillerCenterResponse>
{
  static const char* value()
  {
    return DataType< ::dg_msgs::XGPillerCenter >::value();
  }
  static const char* value(const ::dg_msgs::XGPillerCenterResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DG_MSGS_MESSAGE_XGPILLERCENTER_H
