# 升降柱暂停/恢复/终止服务
# 一旦调用了这个服务中的暂停，必须给一个对应的恢复才能将控制权给自动模式下
# 但调用了暂停后仍然可以使用手动控制，因为人工权限大于自动权限
string operation_           # pause暂停，recovery恢复，terminate终止，必须是三选一，否则直接拒绝
---
float32 current_height      # 当前高度