(cl:defpackage photinia_msgs-msg
  (:use )
  (:export
   "<MOVETOGOALACTION>"
   "MOVETOGOALACTION"
   "<MOVETOGOALACTIONFEEDBACK>"
   "MOVETOGOALACTIONFEEDBACK"
   "<MOVETOGOALACTIONGOAL>"
   "MOVETOGOALACTIONGOAL"
   "<MOVETOGOALACTIONRESULT>"
   "MOVETOGOALACTIONRESULT"
   "<MOVETOGOALFEEDBACK>"
   "MOVETOGOALFEEDBACK"
   "<MOVETOGOALGOAL>"
   "MOVETOGOALGOAL"
   "<MOVETOGOALRESULT>"
   "MOVETOGOALRESULT"
   "<PIDPARAMS>"
   "PIDPARAMS"
  ))

