; Auto-generated. Do not edit!


(cl:in-package dg_msgs-msg)


;//! \htmlinclude BollardOperationFeedback.msg.html

(cl:defclass <BollardOperationFeedback> (roslisp-msg-protocol:ros-message)
  ((current_height
    :reader current_height
    :initarg :current_height
    :type cl:float
    :initform 0.0))
)

(cl:defclass BollardOperationFeedback (<BollardOperationFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <BollardOperationFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'BollardOperationFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name dg_msgs-msg:<BollardOperationFeedback> is deprecated: use dg_msgs-msg:BollardOperationFeedback instead.")))

(cl:ensure-generic-function 'current_height-val :lambda-list '(m))
(cl:defmethod current_height-val ((m <BollardOperationFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader dg_msgs-msg:current_height-val is deprecated.  Use dg_msgs-msg:current_height instead.")
  (current_height m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <BollardOperationFeedback>) ostream)
  "Serializes a message object of type '<BollardOperationFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'current_height))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <BollardOperationFeedback>) istream)
  "Deserializes a message object of type '<BollardOperationFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'current_height) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<BollardOperationFeedback>)))
  "Returns string type for a message object of type '<BollardOperationFeedback>"
  "dg_msgs/BollardOperationFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'BollardOperationFeedback)))
  "Returns string type for a message object of type 'BollardOperationFeedback"
  "dg_msgs/BollardOperationFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<BollardOperationFeedback>)))
  "Returns md5sum for a message object of type '<BollardOperationFeedback>"
  "9316e2f24599ef5a0ba747910cce59b6")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'BollardOperationFeedback)))
  "Returns md5sum for a message object of type 'BollardOperationFeedback"
  "9316e2f24599ef5a0ba747910cce59b6")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<BollardOperationFeedback>)))
  "Returns full string definition for message of type '<BollardOperationFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 current_height                      # 当前所在高度~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'BollardOperationFeedback)))
  "Returns full string definition for message of type 'BollardOperationFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 current_height                      # 当前所在高度~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <BollardOperationFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <BollardOperationFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'BollardOperationFeedback
    (cl:cons ':current_height (current_height msg))
))
