; Auto-generated. Do not edit!


(cl:in-package dg_msgs-msg)


;//! \htmlinclude CurrentCorrectionPointFeedback.msg.html

(cl:defclass <CurrentCorrectionPointFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass CurrentCorrectionPointFeedback (<CurrentCorrectionPointFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CurrentCorrectionPointFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CurrentCorrectionPointFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name dg_msgs-msg:<CurrentCorrectionPointFeedback> is deprecated: use dg_msgs-msg:CurrentCorrectionPointFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CurrentCorrectionPointFeedback>) ostream)
  "Serializes a message object of type '<CurrentCorrectionPointFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CurrentCorrectionPointFeedback>) istream)
  "Deserializes a message object of type '<CurrentCorrectionPointFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CurrentCorrectionPointFeedback>)))
  "Returns string type for a message object of type '<CurrentCorrectionPointFeedback>"
  "dg_msgs/CurrentCorrectionPointFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CurrentCorrectionPointFeedback)))
  "Returns string type for a message object of type 'CurrentCorrectionPointFeedback"
  "dg_msgs/CurrentCorrectionPointFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CurrentCorrectionPointFeedback>)))
  "Returns md5sum for a message object of type '<CurrentCorrectionPointFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CurrentCorrectionPointFeedback)))
  "Returns md5sum for a message object of type 'CurrentCorrectionPointFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CurrentCorrectionPointFeedback>)))
  "Returns full string definition for message of type '<CurrentCorrectionPointFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CurrentCorrectionPointFeedback)))
  "Returns full string definition for message of type 'CurrentCorrectionPointFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CurrentCorrectionPointFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CurrentCorrectionPointFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'CurrentCorrectionPointFeedback
))
