(cl:in-package dg_msgs-srv)
(cl:export '(DATA_COLLECT-VAL
          DATA_COLLECT
          TOPIC_LIDAR-VAL
          TOPIC_LIDAR
          COLLECTION_FRAMES-VAL
          COLLECTION_FRAMES
          PATH_SOURCE-VAL
          PATH_SOURCE
          PATH_TARGET-VAL
          PATH_TARGET
          PCD_TARGET-VAL
          PCD_TARGET
          STATISTICAL_FILTER_SOURCE-VAL
          STATISTICAL_FILTER_SOURCE
          STATISTICAL_FILTER_TARGET-VAL
          STATISTICAL_FILTER_TARGET
          USE_FPFH-VAL
          USE_FPFH
          CROP-VAL
          CROP
          CROPBOX_SOURCE-VAL
          CROPBOX_SOURCE
          CROPBOX_TARGET-VAL
          CROPBOX_TARGET
          INIT_POSE-VAL
          INIT_POSE
          TRANSFORM-VAL
          TRANSFORM
          STATE_INFO-VAL
          STATE_INFO
))